# -*- coding: utf-8 -*-
"""BYDscenarios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fFx53QmQrKpYHI04hvAcbFbhWydQHPbD
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Generating revenue projections
def generate_revenue_projections(real_revenues, years, growth_rates):
    projections = {}
    last_real_year = len(real_revenues)
    for scenario, rate in growth_rates.items():
        scenario_revenue = real_revenues.copy()
        for year in range(last_real_year, years):
            new_revenue = scenario_revenue[-1] * (1 + rate)
            scenario_revenue.append(new_revenue)
        projections[scenario] = scenario_revenue
    return projections

# Revenues
real_revenues = [682.291_828_000*0.14, 602.315_354_000*0.14, 424.060_635_000*0.14, 602.315_354_000*0.14, 682.291_828_000*0.14]  # Example values for 2020-2024 in USD

# Years
total_years = 10  # From 2020 to 2034

# Growth rates for each scenario
growth_rates = {
    "Pessimistic": -0.02,  # -2% growth per year
    "Neutral": 0.05,       # 5% growth per year
    "Optimistic": 0.1      # 10% growth per year
}


projections = generate_revenue_projections(real_revenues, total_years, growth_rates)


projection_df = pd.DataFrame(projections)
projection_df.index = range(2020, 2020 + total_years)

# Plot
plt.figure(figsize=(10,6))
plt.plot(projection_df.index, projection_df['Pessimistic'], label='Pessimistic', color='red', linestyle='--')
plt.plot(projection_df.index, projection_df['Neutral'], label='Neutral', color='blue', linestyle='-')
plt.plot(projection_df.index, projection_df['Optimistic'], label='Optimistic', color='green', linestyle='-.')

# Labels and Title
plt.title('Revenue Projections for BYD ', fontsize=14)
plt.xlabel('Year', fontsize=12)
plt.ylabel('Revenue (in billions USD)', fontsize=12)
plt.legend()
plt.grid(True)
plt.xticks(np.arange(2020, 2020 + total_years + 1, 1))
plt.show()


projection_df